import Head from 'next/head'
import { Inter } from 'next/font/google'
import Button from '@/components/Button'
import FancyButton from '@/components/FancyButton'
import Highlight from '@/components/Highlight'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Button</h1>
        <Button>Button</Button>
        <h1>Fancy Button</h1>
        <FancyButton>Fancy Button</FancyButton>
        <h1>Highlight</h1>
        <Highlight text="highlighted text" />
        <h1>Just span</h1>
        <span>
          <b>highlighted</b> text
        </span>
      </main>
    </>
  )
}
